### PR TITLE
add support for level-scuttlebutt

### PR DESCRIPTION
**Pull request by dominictarr**
with tests!

### CODE REVIEW

**Comment by Raynos** [comment]
Published as v0.2.1

I removed the local cleanup of `_store` otherwise the handshake sends "PUSH 1, DELETE 2" instead of "PUSH 1, PUSH 2, DELETE 2"

**Comment by dominictarr** [comment]
That was intended, if you send DELETE 2, then PUSH 2 is now irrelevant. 
you just need to know it's been deleted, not what it was.

**Comment by Raynos** [comment]
Then the code simply needs to be tolerant to malformed incoming data. i.e. if it's DELETE 2 it doesnt need to care about PUSH 2.

**Comment by Raynos** [comment]
I understand now. Cleaned up history properly in 0.2.2

**Pull request merged**
